In [1]:
import pandas as pd
import numpy as np
import joblib

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [4]:


print("All libraries imported successfully!")

All libraries imported successfully!

In [5]:

application_df = pd.read_csv("dataset/application_record.csv")
credit_df = pd.read_csv("dataset/credit_record.csv")

print("Application Dataset Shape:", application_df.shape)
print("Credit Dataset Shape:", credit_df.shape)

Application Dataset Shape: (438557, 18)
Credit Dataset Shape: (1048575, 3)

In [6]:
application_df.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0

In [7]:
credit_df.head()

        ID  MONTHS_BALANCE STATUS
0  5001711               0      X
1  5001711              -1      0
2  5001711              -2      0
3  5001711              -3      0
4  5001712               0      C

In [8]:
# Information about the application dataset
application_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 438557 entries, 0 to 438556
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   438557 non-null  int64
 1   CODE_GENDER          438557 non-null  str
 2   FLAG_OWN_CAR         438557 non-null  str
 3   FLAG_OWN_REALTY      438557 non-null  str
 4   CNT_CHILDREN         438557 non-null  int64
 5   AMT_INCOME_TOTAL     438557 non-null  float64
 6   NAME_INCOME_TYPE     438557 non-null  str
 7   NAME_EDUCATION_TYPE  438557 non-null  str
 8   NAME_FAMILY_STATUS   438557 non-null  str
 9   NAME_HOUSING_TYPE    438557 non-null  str
 10  DAYS_BIRTH           438557 non-null  int64
 11  DAYS_EMPLOYED        438557 non-null  int64
 12  FLAG_MOBIL           438557 non-null  int64
 13  FLAG_WORK_PHONE      438557 non-null  int64
 14  FLAG_PHONE           438557 non-null  int64
 15  FLAG_EMAIL           438557 non-null  int64
 16  OCCUPATION_TYPE      304354 non-null  str
 17  CNT_FAM_MEMBERS      438557 non-null  float64
dtypes: float64(2), int64(8), str(8)
memory usage: 60.2 MB

In [9]:
# Information about the credit dataset
credit_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   ID              1048575 non-null  int64
 1   MONTHS_BALANCE  1048575 non-null  int64
 2   STATUS          1048575 non-null  str
dtypes: int64(2), str(1)
memory usage: 24.0 MB

In [10]:
# Check missing values in application dataset
application_df.isnull().sum()

ID                          0
CODE_GENDER                 0
FLAG_OWN_CAR                0
FLAG_OWN_REALTY             0
CNT_CHILDREN                0
AMT_INCOME_TOTAL            0
NAME_INCOME_TYPE            0
NAME_EDUCATION_TYPE         0
NAME_FAMILY_STATUS          0
NAME_HOUSING_TYPE           0
DAYS_BIRTH                  0
DAYS_EMPLOYED               0
FLAG_MOBIL                  0
FLAG_WORK_PHONE             0
FLAG_PHONE                  0
FLAG_EMAIL                  0
OCCUPATION_TYPE        134203
CNT_FAM_MEMBERS             0
dtype: int64

In [11]:
# Check missing values in credit dataset
credit_df.isnull().sum()

ID                0
MONTHS_BALANCE    0
STATUS            0
dtype: int64

In [12]:
# Merge application and credit datasets using the common 'ID' column
merged_df = pd.merge(application_df, credit_df, on='ID', how='inner')

# Display the shape of the merged dataset
print("Merged Dataset Shape:", merged_df.shape)

Merged Dataset Shape: (777715, 20)

In [13]:
# Display the first 5 rows of the merged dataset
merged_df.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,MONTHS_BALANCE,STATUS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,0,C
1,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,-1,C
2,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,-2,C
3,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,-3,C
4,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,-4,C

In [14]:
# Display information about the merged dataset
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 777715 entries, 0 to 777714
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   777715 non-null  int64
 1   CODE_GENDER          777715 non-null  str
 2   FLAG_OWN_CAR         777715 non-null  str
 3   FLAG_OWN_REALTY      777715 non-null  str
 4   CNT_CHILDREN         777715 non-null  int64
 5   AMT_INCOME_TOTAL     777715 non-null  float64
 6   NAME_INCOME_TYPE     777715 non-null  str
 7   NAME_EDUCATION_TYPE  777715 non-null  str
 8   NAME_FAMILY_STATUS   777715 non-null  str
 9   NAME_HOUSING_TYPE    777715 non-null  str
 10  DAYS_BIRTH           777715 non-null  int64
 11  DAYS_EMPLOYED        777715 non-null  int64
 12  FLAG_MOBIL           777715 non-null  int64
 13  FLAG_WORK_PHONE      777715 non-null  int64
 14  FLAG_PHONE           777715 non-null  int64
 15  FLAG_EMAIL           777715 non-null  int64
 16  OCCUPATION_TYPE      537667 non-null  str
 17  CNT_FAM_MEMBERS      777715 non-null  float64
 18  MONTHS_BALANCE       777715 non-null  int64
 19  STATUS               777715 non-null  str
dtypes: float64(2), int64(9), str(9)
memory usage: 118.7 MB

In [15]:
# Check missing values in the merged dataset
merged_df.isnull().sum()

ID                          0
CODE_GENDER                 0
FLAG_OWN_CAR                0
FLAG_OWN_REALTY             0
CNT_CHILDREN                0
AMT_INCOME_TOTAL            0
NAME_INCOME_TYPE            0
NAME_EDUCATION_TYPE         0
NAME_FAMILY_STATUS          0
NAME_HOUSING_TYPE           0
DAYS_BIRTH                  0
DAYS_EMPLOYED               0
FLAG_MOBIL                  0
FLAG_WORK_PHONE             0
FLAG_PHONE                  0
FLAG_EMAIL                  0
OCCUPATION_TYPE        240048
CNT_FAM_MEMBERS             0
MONTHS_BALANCE              0
STATUS                      0
dtype: int64

In [16]:
merged_df.shape

(777715, 20)

In [17]:
print("Duplicate Rows:", merged_df.duplicated().sum())

Duplicate Rows: 0

In [18]:
# Remove duplicate rows
merged_df = merged_df.drop_duplicates()

print("Dataset Shape After Removing Duplicates:", merged_df.shape)

Dataset Shape After Removing Duplicates: (777715, 20)

In [19]:
# Remove the ID column
merged_df = merged_df.drop("ID", axis=1)

print("ID column removed successfully.")

ID column removed successfully.

In [20]:
# Check missing values
merged_df.isnull().sum()

CODE_GENDER                 0
FLAG_OWN_CAR                0
FLAG_OWN_REALTY             0
CNT_CHILDREN                0
AMT_INCOME_TOTAL            0
NAME_INCOME_TYPE            0
NAME_EDUCATION_TYPE         0
NAME_FAMILY_STATUS          0
NAME_HOUSING_TYPE           0
DAYS_BIRTH                  0
DAYS_EMPLOYED               0
FLAG_MOBIL                  0
FLAG_WORK_PHONE             0
FLAG_PHONE                  0
FLAG_EMAIL                  0
OCCUPATION_TYPE        240048
CNT_FAM_MEMBERS             0
MONTHS_BALANCE              0
STATUS                      0
dtype: int64

In [21]:
merged_df["OCCUPATION_TYPE"] = merged_df["OCCUPATION_TYPE"].fillna("Unknown")

In [22]:
merged_df.isnull().sum()

CODE_GENDER            0
FLAG_OWN_CAR           0
FLAG_OWN_REALTY        0
CNT_CHILDREN           0
AMT_INCOME_TOTAL       0
NAME_INCOME_TYPE       0
NAME_EDUCATION_TYPE    0
NAME_FAMILY_STATUS     0
NAME_HOUSING_TYPE      0
DAYS_BIRTH             0
DAYS_EMPLOYED          0
FLAG_MOBIL             0
FLAG_WORK_PHONE        0
FLAG_PHONE             0
FLAG_EMAIL             0
OCCUPATION_TYPE        0
CNT_FAM_MEMBERS        0
MONTHS_BALANCE         0
STATUS                 0
dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

for column in merged_df.columns:
    if merged_df[column].dtype == 'object':
        merged_df[column] = label_encoder.fit_transform(merged_df[column])

print("Categorical columns converted to numeric successfully.")

Categorical columns converted to numeric successfully.

In [24]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 777715 entries, 0 to 777714
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   CODE_GENDER          777715 non-null  str
 1   FLAG_OWN_CAR         777715 non-null  str
 2   FLAG_OWN_REALTY      777715 non-null  str
 3   CNT_CHILDREN         777715 non-null  int64
 4   AMT_INCOME_TOTAL     777715 non-null  float64
 5   NAME_INCOME_TYPE     777715 non-null  str
 6   NAME_EDUCATION_TYPE  777715 non-null  str
 7   NAME_FAMILY_STATUS   777715 non-null  str
 8   NAME_HOUSING_TYPE    777715 non-null  str
 9   DAYS_BIRTH           777715 non-null  int64
 10  DAYS_EMPLOYED        777715 non-null  int64
 11  FLAG_MOBIL           777715 non-null  int64
 12  FLAG_WORK_PHONE      777715 non-null  int64
 13  FLAG_PHONE           777715 non-null  int64
 14  FLAG_EMAIL           777715 non-null  int64
 15  OCCUPATION_TYPE      777715 non-null  str
 16  CNT_FAM_MEMBERS      777715 non-null  float64
 17  MONTHS_BALANCE       777715 non-null  int64
 18  STATUS               777715 non-null  str
dtypes: float64(2), int64(8), str(9)
memory usage: 112.7 MB

In [25]:
merged_df.columns

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'MONTHS_BALANCE',
       'STATUS'],
      dtype='str')

In [26]:
list(merged_df.columns)

['CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'FLAG_MOBIL',
 'FLAG_WORK_PHONE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'MONTHS_BALANCE',
 'STATUS']

In [27]:
merged_df["STATUS"].value_counts()

STATUS
C    329536
0    290654
X    145950
1      8747
5      1527
2       801
3       286
4       214
Name: count, dtype: int64

In [28]:
# Convert STATUS into binary target
merged_df["TARGET"] = merged_df["STATUS"].apply(
    lambda x: 0 if x in ["C", "X", "0"] else 1
)

# Check the new target values
print(merged_df["TARGET"].value_counts())

TARGET
0    766140
1     11575
Name: count, dtype: int64

In [29]:
merged_df = merged_df.drop("STATUS", axis=1)

print("STATUS column removed successfully.")

STATUS column removed successfully.

In [30]:
merged_df["TARGET"].value_counts()

TARGET
0    766140
1     11575
Name: count, dtype: int64

In [31]:
# Separate input features (X) and target (y)

X = merged_df.drop("TARGET", axis=1)
y = merged_df["TARGET"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (777715, 18)
Target Shape: (777715,)

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (622172, 18)
Testing Data: (155543, 18)

In [33]:
merged_df.select_dtypes(include=['object']).columns

C:\Users\Vardh\AppData\Local\Temp\ipykernel_2896\1195749936.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  merged_df.select_dtypes(include=['object']).columns

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_INCOME_TYPE',
       'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
       'OCCUPATION_TYPE'],
      dtype='str')

In [34]:
LabelEncoder()

LabelEncoder()

In [35]:
merged_df.select_dtypes(include=['object'])

C:\Users\Vardh\AppData\Local\Temp\ipykernel_2896\1888710302.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  merged_df.select_dtypes(include=['object'])

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OCCUPATION_TYPE
0,M,Y,Y,Working,Higher education,Civil marriage,Rented apartment,Unknown
1,M,Y,Y,Working,Higher education,Civil marriage,Rented apartment,Unknown
2,M,Y,Y,Working,Higher education,Civil marriage,Rented apartment,Unknown
3,M,Y,Y,Working,Higher education,Civil marriage,Rented apartment,Unknown
4,M,Y,Y,Working,Higher education,Civil marriage,Rented apartment,Unknown
...,...,...,...,...,...,...,...,...
777710,M,N,Y,Working,Secondary / secondary special,Single / not married,Rented apartment,Laborers
777711,M,N,Y,Working,Secondary / secondary special,Single / not married,Rented apartment,Laborers
777712,M,N,Y,Working,Secondary / secondary special,Single / not married,Rented apartment,Laborers
777713,M,N,Y,Working,Secondary / secondary special,Single / not married,Rented apartment,Laborers
777714,M,N,Y,Working,Secondary / secondary special,Single / not married,Rented apartment,Laborers

In [36]:
merged_df.select_dtypes(include=['object']).columns

C:\Users\Vardh\AppData\Local\Temp\ipykernel_2896\1195749936.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  merged_df.select_dtypes(include=['object']).columns

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_INCOME_TYPE',
       'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
       'OCCUPATION_TYPE'],
      dtype='str')

In [37]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

object_columns = merged_df.select_dtypes(include=['object']).columns

for col in object_columns:
    merged_df[col] = le.fit_transform(merged_df[col].astype(str))

print("Encoding completed successfully!")

C:\Users\Vardh\AppData\Local\Temp\ipykernel_2896\723097110.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_columns = merged_df.select_dtypes(include=['object']).columns

Encoding completed successfully!

In [38]:
merged_df.select_dtypes(include=['object']).columns

Index([], dtype='str')

In [39]:
X = merged_df.drop("TARGET", axis=1)
y = merged_df["TARGET"]

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [41]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train, y_train)

c:\Users\Vardh\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [42]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Predict using the trained model
y_pred = log_model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Logistic Regression Accuracy:", accuracy)

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Logistic Regression Accuracy: 0.9853095285548048

Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99    153258
           1       0.00      0.00      0.00      2285

    accuracy                           0.99    155543
   macro avg       0.49      0.50      0.50    155543
weighted avg       0.97      0.99      0.98    155543


Confusion Matrix:
[[153258      0]
 [  2285      0]]

c:\Users\Vardh\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Vardh\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Vardh\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [43]:
from sklearn.tree import DecisionTreeClassifier

# Create the model
dt_model = DecisionTreeClassifier(random_state=42)

# Train the model
dt_model.fit(X_train, y_train)

# Predict
dt_pred = dt_model.predict(X_test)

# Accuracy
from sklearn.metrics import accuracy_score

dt_accuracy = accuracy_score(y_test, dt_pred)

print("Decision Tree Accuracy:", dt_accuracy)

Decision Tree Accuracy: 0.9824485833499418

In [44]:
from sklearn.ensemble import RandomForestClassifier

# Create the model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train
rf_model.fit(X_train, y_train)

# Predict
rf_pred = rf_model.predict(X_test)

# Accuracy
rf_accuracy = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy:", rf_accuracy)

Random Forest Accuracy: 0.982609310608642

In [45]:
from xgboost import XGBClassifier

# Create the model
xgb_model = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

# Train
xgb_model.fit(X_train, y_train)

# Predict
xgb_pred = xgb_model.predict(X_test)

# Accuracy
xgb_accuracy = accuracy_score(y_test, xgb_pred)

print("XGBoost Accuracy:", xgb_accuracy)

XGBoost Accuracy: 0.9858945757764734

In [46]:
import joblib

joblib.dump(xgb_model, "model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [47]:
type(X)

pandas.DataFrame

In [48]:
print(X.shape)

(777715, 18)

In [49]:
print(X.columns.tolist())

['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'MONTHS_BALANCE']

In [50]:
type(merged_df)

pandas.DataFrame

In [51]:
from sklearn.preprocessing import LabelEncoder
import joblib

encoders = {}

object_columns = merged_df.select_dtypes(include=['object']).columns

for col in object_columns:
    le = LabelEncoder()
    merged_df[col] = le.fit_transform(merged_df[col].astype(str))
    encoders[col] = le

joblib.dump(encoders, "encoders.pkl")

print("Encoders saved successfully!")

Encoders saved successfully!

In [52]:
list(encoders.keys())

[]

In [53]:
application_df.dtypes

ID                       int64
CODE_GENDER                str
FLAG_OWN_CAR               str
FLAG_OWN_REALTY            str
CNT_CHILDREN             int64
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE           str
NAME_EDUCATION_TYPE        str
NAME_FAMILY_STATUS         str
NAME_HOUSING_TYPE          str
DAYS_BIRTH               int64
DAYS_EMPLOYED            int64
FLAG_MOBIL               int64
FLAG_WORK_PHONE          int64
FLAG_PHONE               int64
FLAG_EMAIL               int64
OCCUPATION_TYPE            str
CNT_FAM_MEMBERS        float64
dtype: object

In [54]:
credit_df.dtypes

ID                int64
MONTHS_BALANCE    int64
STATUS              str
dtype: object

In [55]:
application_df.dtypes

ID                       int64
CODE_GENDER                str
FLAG_OWN_CAR               str
FLAG_OWN_REALTY            str
CNT_CHILDREN             int64
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE           str
NAME_EDUCATION_TYPE        str
NAME_FAMILY_STATUS         str
NAME_HOUSING_TYPE          str
DAYS_BIRTH               int64
DAYS_EMPLOYED            int64
FLAG_MOBIL               int64
FLAG_WORK_PHONE          int64
FLAG_PHONE               int64
FLAG_EMAIL               int64
OCCUPATION_TYPE            str
CNT_FAM_MEMBERS        float64
dtype: object

In [56]:
merged_df = pd.merge(application_df, credit_df, on="ID", how="inner")

merged_df["OCCUPATION_TYPE"] = merged_df["OCCUPATION_TYPE"].fillna("Unknown")

merged_df["TARGET"] = merged_df["STATUS"].apply(
    lambda x: 0 if x in ["C", "X", "0"] else 1
)

merged_df = merged_df.drop(["ID", "STATUS"], axis=1)

print("Merged dataset created successfully!")

Merged dataset created successfully!

In [57]:
from sklearn.preprocessing import LabelEncoder
import joblib

encoders = {}

object_columns = merged_df.select_dtypes(include=["object", "string"]).columns

for col in object_columns:
    le = LabelEncoder()
    merged_df[col] = le.fit_transform(merged_df[col].astype(str))
    encoders[col] = le

joblib.dump(encoders, "encoders.pkl")

print("Encoders saved successfully!")
print(encoders.keys())

Encoders saved successfully!
dict_keys(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE'])

In [58]:
X = merged_df.drop("TARGET", axis=1)
y = merged_df["TARGET"]

In [59]:
joblib.dump(xgb_model, "model.pkl")

['model.pkl']

In [62]:
negative = (y_train == 0).sum()
positive = (y_train == 1).sum()

scale = negative / positive

print(scale)

65.97222820236814

In [63]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    random_state=42,
    eval_metric="logloss",
    scale_pos_weight=scale
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [64]:
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [65]:
y_pred = xgb_model.predict(X_test)

In [66]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8487427913824473
              precision    recall  f1-score   support

           0       0.99      0.85      0.92    153258
           1       0.07      0.71      0.12      2285

    accuracy                           0.85    155543
   macro avg       0.53      0.78      0.52    155543
weighted avg       0.98      0.85      0.91    155543

In [67]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)

X_train_resampled, y_train_resampled = ros.fit_resample(
    X_train,
    y_train
)

In [68]:
xgb_model.fit(X_train_resampled, y_train_resampled)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [70]:
print(credit_df["STATUS"].value_counts())

STATUS
C    442031
0    383120
X    209230
1     11090
5      1693
2       868
3       320
4       223
Name: count, dtype: int64

In [72]:
print(merged_df.columns)

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'MONTHS_BALANCE',
       'TARGET'],
      dtype='str')

In [73]:
print(credit_df.columns)

Index(['ID', 'MONTHS_BALANCE', 'STATUS'], dtype='str')

In [75]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[130397  22861]
 [   666   1619]]

In [76]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.85      0.92    153258
           1       0.07      0.71      0.12      2285

    accuracy                           0.85    155543
   macro avg       0.53      0.78      0.52    155543
weighted avg       0.98      0.85      0.91    155543

In [77]:
import joblib

joblib.dump(xgb_model, "model.pkl")

['model.pkl']

In [78]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)

xgb_model.fit(X_train_smote, y_train_smote)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)